const nodemailer = require("nodemailer");

var transport = nodemailer.createTransport({
	host: "smtp.mailtrap.io",
	port: 2525,
	auth: {
		user: "14a33843634d5d", //generated by Mailtrap
		pass: "0e7d006f2e3549" //generated by Mailtrap
	}
});

var confirm_email_options = ({ email, url }) => {
	return {
		from: '"Blackboard Team" <blackboard@example.com>',
		to: email,
		subject: "Confirm email",
		html: `Please click this email to confirm your email: <a href="${url}"> ${url}</a>`
	};
};

var reset_pass_options = ({ email, url }) => {
	return {
		from: '"Blackboard Team" <blackboard@example.com>',
		to: email,
		subject: "Password reset",

		html: `You are receiving this because you (or someone else) have requested the reset of the password for your account.
    <br/> <a href="${url}"> ${url}</a>
    <br/>
    If you did not request this, please ignore this email and your password will remain unchanged `
	};
};

// mailer.transport.verify(function(error, success) {
//     if (error) {
//          console.log(error);
//     } else {
//          console.log('Server is ready to take our messages');
//     }
//  });

module.exports = {
	transport: transport,
	options: {
		confirm_email_options,
		reset_pass_options
	}
};
